logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "test@traefik-server.local"
storage = "/traefik-acme/account"
entryPoint = "https"
OnHostRule = true
onDemand = true
caServer = "http://node-acme-server/directory"
acmeLogging = true

[web]
address = ":8080"

[file]
filename = "/traefik/rules.toml"
watch = true
