version: "2"
services:
  domain-proxy:
    image: qiushihe/domain-proxy
    build: ./domain-proxy
    ports:
      - "9000:9000"
    cap_add:
      - NET_ADMIN
    environment:
      DOMAIN_PROXY_FE_1: "lala1.com:9000"
      DOMAIN_PROXY_BE_1: "minio-server-lala1:9000"
      DOMAIN_PROXY_FE_2: "lala2.com:9000"
      DOMAIN_PROXY_BE_2: "minio-server-lala2:9000"
  minio-server-lala1:
    image: qiushihe/minio-server
    build: ./minio-server
    volumes:
      - ./volumes/lala1:/minio-data
    environment:
      MINIO_SERVER_ACCESS_KEY: "accesskey1"
      MINIO_SERVER_SECRET_KEY: "secretkey1"
  minio-server-lala2:
    image: qiushihe/minio-server
    build: ./minio-server
    volumes:
      - ./volumes/lala2:/minio-data
    environment:
      MINIO_SERVER_ACCESS_KEY: "accesskey2"
      MINIO_SERVER_SECRET_KEY: "secretkey2"
