version: "2"
services:
  nfs-server:
    image: qiushihe/nfs-server:2017-04-06
    cap_add:
      - SYS_ADMIN
    volumes:
      - nfs-data:/exports
    environment:
      NFS_SERVER_SHARES: "lala1 lala2"
  nfs-client:
    image: qiushihe/nfs-client
    build: ./nfs-client
    cap_add:
      - SYS_ADMIN
    environment:
      NFS_CLIENT_NFS_SERVER: "nfs-server"
      NFS_CLIENT_NFS_SHARE1: "lala1"
      NFS_CLIENT_NFS_SHARE2: "lala2"

volumes:
  nfs-data:
    driver: local
