version: "2"
services:
  domain-proxy:
    image: qiushihe/domain-proxy
    build: ./domain-proxy
    ports:
      - "8080:80"
      - "9000:9000"
    cap_add:
      - NET_ADMIN
    environment:
      DOMAIN_PROXY_FE_1: "lala1.com:80"
      DOMAIN_PROXY_BE_1: "nginx-server-lala1:80"
      DOMAIN_PROXY_FE_2: "lala1.com:9000"
      DOMAIN_PROXY_BE_2: "minio-server-lala1:9000"
  mysql-server:
    image: qiushihe/mysql-server
    build: ./mysql-server
    volumes:
      - ./volumes/mysql-server:/mysql-data
    environment:
      MYSQL_SERVER_ROOT_PASSWORD: "changeme"
      MYSQL_SERVER_USER_1: "lala1"
      MYSQL_SERVER_PASSWORD_1: "lala1pass"
  nginx-server-lala1:
    image: qiushihe/nginx-server
    build: ./nginx-server
    volumes:
      - ./volumes/lala1:/web-data
    links:
      - mysql-server
  minio-server-lala1:
    image: qiushihe/minio-server
    build: ./minio-server
    volumes:
      - ./volumes/lala1:/minio-data
    environment:
      MINIO_SERVER_ACCESS_KEY: "accesskey1"
      MINIO_SERVER_SECRET_KEY: "secretkey1"
