version: "2"
services:
  le-servo-server:
    image: qiushihe/le-servo-server
    build: ../le-servo-server
    links:
      - "web-server-1:lala1.com"
    environment:
      LE_SERVO_SERVER_HOST_NAME: "le-servo-server"
      LE_SERVO_SERVER_PORT: "80"
  web-server-1:
    image: qiushihe/nginx-server
    build: ../nginx-server
    volumes:
      - ./volumes/lala1:/web-data
    ports:
      - "8080:80"
      - "8443:443"
