version: "2"
services:
  nfs-server:
    image: qiushihe/nfs-server
    build: ../nfs-server
    cap_add:
      - SYS_ADMIN
    volumes:
      - nfs-data:/exports
    environment:
      NFS_SERVER_SHARE_1: "web1"
  web-server:
    image: qiushihe/nginx-server
    build: ../nginx-server
    cap_add:
      - SYS_ADMIN
    ports:
      - "8080:80"
    environment:
      NGINX_SERVER_NFS_HOST: "nfs-server"
      NGINX_SERVER_NFS_SHARE: "web1"

volumes:
  nfs-data:
    driver: local
