version: "2"
services:
  boulder-server:
    image: qiushihe/boulder-server:2017-03-25
    depends_on:
      - domain-proxy
    environment:
      BOULDER_SERVER_FAKE_DNS_HOST: "domain-proxy"
      BOULDER_SERVER_FAKE_DNS_DOMAIN_1: "lala1.com"
      BOULDER_SERVER_FAKE_DNS_DOMAIN_2: "lala2.com"
  domain-proxy:
    image: qiushihe/domain-proxy
    build: ../domain-proxy
    ports:
      - "8080:80"
      - "8443:443"
    cap_add:
      - NET_ADMIN
    environment:
      DOMAIN_PROXY_USE_CERTBOT: "yes"
      DOMAIN_PROXY_BOULDER_HOST: "boulder-server"
      DOMAIN_PROXY_FE_1: "lala1.com:80"
      DOMAIN_PROXY_BE_1: "nginx-server-1:80"
      DOMAIN_PROXY_FE_2: "lala1.com:443"
      DOMAIN_PROXY_BE_2: "nginx-server-1:80"
      DOMAIN_PROXY_FE_3: "lala2.com:80"
      DOMAIN_PROXY_BE_3: "nginx-server-2:80"
      DOMAIN_PROXY_FE_4: "lala2.com:443"
      DOMAIN_PROXY_BE_4: "nginx-server-2:80"
  nginx-server-1:
    image: qiushihe/nginx-server
    build: ../nginx-server
    volumes:
      - ../volumes/lala1:/web-data
  nginx-server-2:
    image: qiushihe/nginx-server
    build: ../nginx-server
    volumes:
      - ../volumes/lala2:/web-data
