version: "2"
services:
  # boulder-server:
  #   image: qiushihe/boulder-server:2017-03-25
  #   depends_on:
  #     - traefik-server
  #   environment:
  #     BOULDER_SERVER_FAKE_DNS_HOST: "traefik-server"
  #     BOULDER_SERVER_FAKE_DNS_DOMAIN_1: "lala1.com"
  #     BOULDER_SERVER_FAKE_DNS_DOMAIN_2: "lala2.com"
  le-servo-server:
    image: qiushihe/le-servo-server
    build: ../le-servo-server
    environment:
      LE_SERVO_SERVER_HOST_NAME: "le-servo-server"
      LE_SERVO_SERVER_PORT: "80"
  traefik-server:
    image: qiushihe/traefik-server
    build: ../traefik-server
    ports:
      - "8888:8080"
      - "8080:80"
      - "8443:443"
    cap_add:
      - NET_ADMIN
    environment:
      TRAEFIK_SERVER_CA_SERVER: "http://le-servo-server/directory"
      TRAEFIK_SERVER_FE_1: "Host:lala1.com"
      TRAEFIK_SERVER_BE_1: "http://web-server-1:80"
      TRAEFIK_SERVER_FE_2: "Host:lala2.com"
      TRAEFIK_SERVER_BE_2: "http://web-server-2:80"
  web-server-1:
    image: qiushihe/apache-server
    build: ../apache-server
    volumes:
      - ../volumes/lala1:/web-data
    ports:
      - "9999:80"
  web-server-2:
    image: qiushihe/nginx-server
    build: ../nginx-server
    volumes:
      - ../volumes/lala2:/web-data
