apiVersion: v1
kind: Service
metadata:
  name: domain-proxy
spec:
  selector:
    service: domain-proxy
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    name: "80-tcp"
    port: 80
  - protocol: "TCP"
    name: "9000-tcp"
    port: 9000
    targetPort: 9000
