apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  clusterIP: None
  selector:
    service: nfs-server
  ports:
  - protocol: UDP
    name: "111-udp"
    port: 111
  - protocol: TCP
    name: "2049-tcp"
    port: 2049
