apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-server-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: nginx-server-1
    spec:
      containers:
      - image: qiushihe/nginx-server:1.0.0
        name: nginx-server-1
        securityContext:
          privileged: true
