apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-server-web1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: web-server-web1
    spec:
      containers:
      - image: qiushihe/apache-server:2017-04-28
        name: web-server-web1
        ports:
        - containerPort: 80
        securityContext:
          capabilities:
            add: [SYS_ADMIN]
        env:
        - name: APACHE_SERVER_USER_ID
          value: "8980"
        - name: APACHE_SERVER_GROUP_ID
          value: "8981"
        - name: APACHE_SERVER_NFS_HOST
          value: "nfs-server"
        - name: APACHE_SERVER_NFS_SHARE
          value: "web1"
